[package]
name = "tarut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { version = "0.7.0", features = ["im"] }
openssl = "0.10.38"
bs58 = "0.4.0"
socks = "0.3.4"